# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edge.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_edge(object):
    def setupUi(self, Form_edge):
        Form_edge.setObjectName("Form_edge")
        Form_edge.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form_edge)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form_edge)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(Form_edge)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Form_edge)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form_edge)
        QtCore.QMetaObject.connectSlotsByName(Form_edge)

    def retranslateUi(self, Form_edge):
        _translate = QtCore.QCoreApplication.translate
        Form_edge.setWindowTitle(_translate("Form_edge", "Form"))
        self.pushButton.setText(_translate("Form_edge", "边缘检测"))
        self.label.setText(_translate("Form_edge", "算子类型"))
        self.comboBox.setItemText(0, _translate("Form_edge", "roberts"))
        self.comboBox.setItemText(1, _translate("Form_edge", "prewitt"))
        self.comboBox.setItemText(2, _translate("Form_edge", "sobel"))
        self.comboBox.setItemText(3, _translate("Form_edge", "log"))
