# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fourier.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_f(object):
    def setupUi(self, Form_f):
        Form_f.setObjectName("Form_f")
        Form_f.resize(347, 262)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_f)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_Fimg = QtWidgets.QPushButton(Form_f)
        self.pb_Fimg.setObjectName("pb_Fimg")
        self.verticalLayout.addWidget(self.pb_Fimg)
        self.pb_filter = QtWidgets.QPushButton(Form_f)
        self.pb_filter.setObjectName("pb_filter")
        self.verticalLayout.addWidget(self.pb_filter)
        self.label_2 = QtWidgets.QLabel(Form_f)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.le_d0 = QtWidgets.QLineEdit(Form_f)
        self.le_d0.setObjectName("le_d0")
        self.verticalLayout.addWidget(self.le_d0)
        self.label_3 = QtWidgets.QLabel(Form_f)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.le_n = QtWidgets.QLineEdit(Form_f)
        self.le_n.setObjectName("le_n")
        self.verticalLayout.addWidget(self.le_n)
        self.label = QtWidgets.QLabel(Form_f)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.type = QtWidgets.QComboBox(Form_f)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.verticalLayout.addWidget(self.type)
        self.label_4 = QtWidgets.QLabel(Form_f)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.kind = QtWidgets.QComboBox(Form_f)
        self.kind.setObjectName("kind")
        self.kind.addItem("")
        self.kind.addItem("")
        self.kind.addItem("")
        self.verticalLayout.addWidget(self.kind)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_f)
        QtCore.QMetaObject.connectSlotsByName(Form_f)

    def retranslateUi(self, Form_f):
        _translate = QtCore.QCoreApplication.translate
        Form_f.setWindowTitle(_translate("Form_f", "Form"))
        self.pb_Fimg.setText(_translate("Form_f", "显示频谱图"))
        self.pb_filter.setText(_translate("Form_f", "滤波"))
        self.label_2.setText(_translate("Form_f", "截止频率"))
        self.label_3.setText(_translate("Form_f", "阶数"))
        self.label.setText(_translate("Form_f", "高通-hp,低通-lp"))
        self.type.setItemText(0, _translate("Form_f", "lp"))
        self.type.setItemText(1, _translate("Form_f", "hp"))
        self.label_4.setText(_translate("Form_f", "滤波器"))
        self.kind.setItemText(0, _translate("Form_f", "butterworth"))
        self.kind.setItemText(1, _translate("Form_f", "ideal"))
        self.kind.setItemText(2, _translate("Form_f", "gaussian"))
