# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"background-color: qradialgradient(cx:0.1, cy:0.1, radius:0.5, fr:0.5, fy:0.5, stop:o rgb(0,170, 247),stop:1 rgb(60, 1,252));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setStyleSheet("font: 13pt \"黑体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"padding:12px;")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 25))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color:qradialgradient(cx:0.1, cy:0.1, radius:0.5, fr:2, fy:0.5, stop:o rgb(0,190, 247),stop:1 rgb(60, 160,252));\n"
"coler: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 150, 0, 255), stop:1 rgba(255, 190, 0, 255));\n"
"border-radius: 10px;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 13pt \"黑体\";\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(150, 125))
        self.listWidget.setStyleSheet("QListWidget {\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:transparent\n"
"}\n"
"QListWidget::item{\n"
"background-color: transparent;\n"
"height:25px;\n"
"padding-left:12px;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item:selected {\n"
"/**background-calor: transparent;*/\n"
"background-color: rgb(220,220,220);\n"
"color: rgb(60, 60, 60);\n"
"}\n"
"color: rgb(255, 255, 255);\n"
"")
        self.listWidget.setLayoutMode(QtWidgets.QListView.Batched)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/solid/fontawesome-free-6.2.1-desktop/fontawesome-free-6.2.1-desktop/svgs/solid/circle-dot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setStyleSheet("font: 13pt \"黑体\";\n"
"background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_2.setMaximumSize(QtCore.QSize(150, 25))
        self.listWidget_2.setStyleSheet("QListWidget {\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item{\n"
"background-color: transparent;\n"
"height:25px;\n"
"padding-left:12px;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item:selected {\n"
"/**background-calor: transparent;*/\n"
"background-color: rgb(220,220,220);\n"
"color: rgb(60, 60, 60);\n"
"}\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget_2.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_2)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setStyleSheet("font: 13pt \"黑体\";\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.listWidget_3 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_3.setMaximumSize(QtCore.QSize(150, 25))
        self.listWidget_3.setStyleSheet("QListWidget {\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item{\n"
"background-color: transparent;\n"
"height:25px;\n"
"padding-left:12px;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item:selected {\n"
"/**background-calor: transparent;*/\n"
"background-color: rgb(220,220,220);\n"
"color: rgb(60, 60, 60);\n"
"}\n"
"")
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget_3.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setStyleSheet("font: 13pt \"黑体\";\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.listWidget_4 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_4.setMaximumSize(QtCore.QSize(150, 50))
        self.listWidget_4.setStyleSheet("QListWidget {\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item{\n"
"background-color: transparent;\n"
"height:25px;\n"
"padding-left:12px;\n"
"}\n"
"/**列表项扫过*/\n"
"QListWidget::item:hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"/**列表项选中*/\n"
"QListWidget::item:selected {\n"
"/**background-calor: transparent;*/\n"
"background-color: rgb(220,220,220);\n"
"color: rgb(60, 60, 60);\n"
"}\n"
"")
        self.listWidget_4.setObjectName("listWidget_4")
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.listWidget_4.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_4)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.LosslessImageRendering|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphicsView_2.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.LosslessImageRendering|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsView_2.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_2.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_2.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_2.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout.addWidget(self.graphicsView_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuimport = QtWidgets.QMenu(self.menuFile)
        self.menuimport.setObjectName("menuimport")
        self.menuexport = QtWidgets.QMenu(self.menuFile)
        self.menuexport.setObjectName("menuexport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionimport_img = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/solid/fontawesome-free-6.2.1-desktop/fontawesome-free-6.2.1-desktop/svgs/solid/file-import.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimport_img.setIcon(icon1)
        self.actionimport_img.setObjectName("actionimport_img")
        self.actionexport_as_png = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/solid/fontawesome-free-6.2.1-desktop/fontawesome-free-6.2.1-desktop/svgs/solid/file-export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexport_as_png.setIcon(icon2)
        self.actionexport_as_png.setObjectName("actionexport_as_png")
        self.actionopen_data_dir = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/solid/fontawesome-free-6.2.1-desktop/fontawesome-free-6.2.1-desktop/svgs/solid/list-ul.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen_data_dir.setIcon(icon3)
        self.actionopen_data_dir.setObjectName("actionopen_data_dir")
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/solid/fontawesome-free-6.2.1-desktop/fontawesome-free-6.2.1-desktop/svgs/solid/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon4)
        self.actionsave.setObjectName("actionsave")
        self.menuimport.addAction(self.actionimport_img)
        self.menuimport.addAction(self.actionopen_data_dir)
        self.menuexport.addAction(self.actionexport_as_png)
        self.menuFile.addAction(self.menuimport.menuAction())
        self.menuFile.addAction(self.menuexport.menuAction())
        self.menuFile.addAction(self.actionsave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionopen_data_dir)
        self.toolBar.addAction(self.actionimport_img)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "自适应"))
        self.label.setText(_translate("MainWindow", "空域图像处理"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "对比度"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "平滑及锐化"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "图形学"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "加噪"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "边缘提取"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "频域图像处理"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "滤波"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "二值化图像形态学"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("MainWindow", "图像二值化"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "数据标签处理"))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "抠图(前景背景分离)"))
        item = self.listWidget_4.item(1)
        item.setText(_translate("MainWindow", "数据增强"))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuimport.setTitle(_translate("MainWindow", "import"))
        self.menuexport.setTitle(_translate("MainWindow", "export"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionimport_img.setText(_translate("MainWindow", "import img"))
        self.actionimport_img.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionexport_as_png.setText(_translate("MainWindow", "export as png"))
        self.actionexport_as_png.setStatusTip(_translate("MainWindow", "export as png"))
        self.actionexport_as_png.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionopen_data_dir.setText(_translate("MainWindow", "open data dir"))
        self.actionopen_data_dir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
import ui.icon_rc
