# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binary.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_bin(object):
    def setupUi(self, Form_bin):
        Form_bin.setObjectName("Form_bin")
        Form_bin.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_bin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(Form_bin)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(Form_bin)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Form_bin)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(Form_bin)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(Form_bin)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form_bin)
        QtCore.QMetaObject.connectSlotsByName(Form_bin)

    def retranslateUi(self, Form_bin):
        _translate = QtCore.QCoreApplication.translate
        Form_bin.setWindowTitle(_translate("Form_bin", "Form"))
        self.pushButton.setText(_translate("Form_bin", "执行"))
        self.label.setText(_translate("Form_bin", "操作类型"))
        self.comboBox.setItemText(0, _translate("Form_bin", "open"))
        self.comboBox.setItemText(1, _translate("Form_bin", "close"))
        self.comboBox.setItemText(2, _translate("Form_bin", "erode"))
        self.comboBox.setItemText(3, _translate("Form_bin", "dilate"))
        self.label_2.setText(_translate("Form_bin", "核大小"))
