# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noise.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_noise(object):
    def setupUi(self, Form_noise):
        Form_noise.setObjectName("Form_noise")
        Form_noise.resize(457, 332)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_noise)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_s = QtWidgets.QPushButton(Form_noise)
        self.pb_s.setObjectName("pb_s")
        self.horizontalLayout.addWidget(self.pb_s)
        self.label = QtWidgets.QLabel(Form_noise)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_sn = QtWidgets.QLineEdit(Form_noise)
        self.le_sn.setObjectName("le_sn")
        self.horizontalLayout.addWidget(self.le_sn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_g = QtWidgets.QPushButton(Form_noise)
        self.pb_g.setObjectName("pb_g")
        self.horizontalLayout_2.addWidget(self.pb_g)
        self.label_2 = QtWidgets.QLabel(Form_noise)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_mean = QtWidgets.QLineEdit(Form_noise)
        self.le_mean.setObjectName("le_mean")
        self.horizontalLayout_2.addWidget(self.le_mean)
        self.label_4 = QtWidgets.QLabel(Form_noise)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_sigma = QtWidgets.QLineEdit(Form_noise)
        self.le_sigma.setObjectName("le_sigma")
        self.horizontalLayout_2.addWidget(self.le_sigma)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_r = QtWidgets.QPushButton(Form_noise)
        self.pb_r.setObjectName("pb_r")
        self.horizontalLayout_3.addWidget(self.pb_r)
        self.label_3 = QtWidgets.QLabel(Form_noise)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.le_rn = QtWidgets.QLineEdit(Form_noise)
        self.le_rn.setObjectName("le_rn")
        self.horizontalLayout_3.addWidget(self.le_rn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form_noise)
        QtCore.QMetaObject.connectSlotsByName(Form_noise)

    def retranslateUi(self, Form_noise):
        _translate = QtCore.QCoreApplication.translate
        Form_noise.setWindowTitle(_translate("Form_noise", "Form"))
        self.pb_s.setText(_translate("Form_noise", "椒盐"))
        self.label.setText(_translate("Form_noise", "噪声程度（0-1）"))
        self.pb_g.setText(_translate("Form_noise", "高斯"))
        self.label_2.setText(_translate("Form_noise", "均值"))
        self.label_4.setText(_translate("Form_noise", "标准差"))
        self.pb_r.setText(_translate("Form_noise", "随机"))
        self.label_3.setText(_translate("Form_noise", "噪点数"))
