# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smooth_sharp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_sp(object):
    def setupUi(self, Form_sp):
        Form_sp.setObjectName("Form_sp")
        Form_sp.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form_sp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_smooth = QtWidgets.QPushButton(Form_sp)
        self.pb_smooth.setObjectName("pb_smooth")
        self.verticalLayout.addWidget(self.pb_smooth)
        self.pb_sharp = QtWidgets.QPushButton(Form_sp)
        self.pb_sharp.setObjectName("pb_sharp")
        self.verticalLayout.addWidget(self.pb_sharp)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form_sp)
        QtCore.QMetaObject.connectSlotsByName(Form_sp)

    def retranslateUi(self, Form_sp):
        _translate = QtCore.QCoreApplication.translate
        Form_sp.setWindowTitle(_translate("Form_sp", "Form"))
        self.pb_smooth.setText(_translate("Form_sp", "图像平滑"))
        self.pb_sharp.setText(_translate("Form_sp", "图像锐化"))
